import Head from 'next/head'
import { useEffect, useState, useMemo } from 'react'
import axios from 'axios'
import NextNProgress from 'nextjs-progressbar'
import Footer from './Footer'
import Navbar from './Navbar'


export default function Layout({ children, title }) {
  const [categories, setCategories] = useState([])

  useEffect(() => {
    axios.get('https://api.escuelajs.co/api/v1/categories')
      .then(res => setCategories(res.data))
      .catch(err => console.log(err))
  }, [])

  const memoizedCategories = useMemo(() => categories, [categories])

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NextNProgress />
        <Navbar categories={memoizedCategories} />
        {children}
        <Footer categories={memoizedCategories} />
      </main>
    </>
  )
}